-- 테이블스페이스 생성
CREATE TABLESPACE TUTORIAL
DATAFILE 'C:\oraclexe\app\oracle\oradata\Tutorial\Tutorial.dbf'
SIZE 10M AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;
-- tablespace의 이름을 tutorial으로 하고, 그 크기를 10MB로 설정하며, 
-- 10MB 초과시 2MB씩 자동 확장생성합니다.

-- SIZE 2048M -- 2기가 바이트 

-- 생성확인
SELECT * FROM dba_TABLESPACES;
SELECT * FROM dba_TABLESPACES WHERE TABLESPACE_NAME = 'TUTORIAL';
