-- 계정 생성
CREATE USER LECTUREEVALUATION IDENTIFIED BY oracle
DEFAULT TABLESPACE LECTUREEVALUATION
TEMPORARY TABLESPACE temp;

-- 생성 확인
SELECT * FROM ALL_USERS;
SELECT * FROM ALL_USERS WHERE USERNAME = 'LECTUREEVALUATION';