-- 테이블 스페이스 생성
CREATE TABLESPACE FILEUPLOAD
DATAFILE 'D:\Study\Study DataFile\file\file.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED
PERMANENT
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

-- 스페이스의 이름을 file로 설정하고
-- 최초 크기는 10mb로 설정하며,
-- 이를초과시 2mb 씩 증가시키며, 
-- 최대 사이즈의 제한은 두지 않겠다...
SELECT * FROM dba_tablespaces;

-- 계정 생성
CREATE USER FILEUPLOAD IDENTIFIED BY oracle
DEFAULT TABLESPACE FILEUPLOAD
TEMPORARY TABLESPACE temp;

SELECT * FROM all_users;

-- 계정 권한 부여
GRANT RESOURCE, CONNECT, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO FILEUPLOAD;

