-- 데이터베이스 생성
CREATE DATABASE SCOTT;

-- LOGIN 생성 (유저의 개념과 비슷)
CREATE LOGIN SCOTT WITH PASSWORD='tiger12345678!',
DEFAULT_DATABASE = SCOTT;

-- SCOTT 데이터베이스를 사용할 수 있는 USER 생성
USE SCOTT
CREATE USER SCOTT FOR LOGIN SCOTT;